### ISSUE TITLE
Build step failing to generate types

### ISSUE THREAD

**Issue by SnorlaxAssist** [roblox-ts/types#1320]
```shell
npm run build
...

types/out/class/ClassGenerator.js:875
                const originalExtends = tsImplInterface.getExtends()[0].getExpression().getText();
                                                                       ^

TypeError: Cannot read properties of undefined (reading 'getExpression')
    at ClassGenerator.generateClass (/home/runner/work/types/types/out/class/ClassGenerator.js:875:72)
    at ClassGenerator.generateClasses (/home/runner/work/types/types/out/class/ClassGenerator.js:998:18)
    at ClassGenerator.<anonymous> (/home/runner/work/types/types/out/class/ClassGenerator.js:1055:18)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/types/types/out/class/ClassGenerator.js:5:58)
```

CI Scheduled build seems to be [failing](https://github.com/roblox-ts/types/actions/runs/11538562973).

**Comment by osyrisrblx** [comment]
Fixed by #1330
